# Generated by Django 2.2.4 on 2020-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='about'),
        ),
    ]
