# Generated by Django 2.2.4 on 2020-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_contact_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Adınız Soyadınız ')),
                ('email', models.EmailField(max_length=35)),
                ('message', models.CharField(max_length=250, verbose_name='Mesajınız ')),
            ],
        ),
    ]
