# Generated by Django 2.2.4 on 2020-05-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_contactformmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormModel',
        ),
    ]
