# Generated by Django 2.2 on 2020-05-22 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200520_1731'),
        ('orders', '0004_auto_20200522_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='product',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
