# Generated by Django 2.2.4 on 2020-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_hover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('men', 'Erkek'), ('women', 'Kadın'), ('unisex', 'Unisex')], default='general', max_length=8),
        ),
    ]
